using MediatR;
using Sudan_Train.Core.Bases;
using Sudan_Train.Data.Results;

namespace Sudan_Train.Core.Features.Authentication.Commands.Login
{
    public class LoginCommand : IRequest<Response<JwtAuthResult>>
    {
        public string? UserName { get; set; }
        public string? Password { get; set; }

        // Device tracking for session management
        public string? DeviceId { get; set; }  // Optional: Generated by frontend
        public string? DeviceName { get; set; } // e.g., "iPhone 14 Pro", "Chrome on Windows"
    }
}

